#!/bin/bash

set -e

RED="\e[31m";
GREEN="\e[32m";
YELLOW="\e[33m";
ENDCOLOR="\e[0m";

function help() {
  echo "immudex-upgrade - (SDK Version) Script for network immudex upgrade.";
  echo "@ 2025 morketsmerke.org";
  echo;
  echo "Usage:";
  echo -e "\t# immudex-upgrade <URL>";
}

echo "Upgrading immudex...";
part=$(blkid | grep 'LABEL="immudex"' | awk '{printf $1}' | cut -d ":" -f 1);

echo -n "  Mounting immudex partition...";
mount $part /mnt >> /dev/null 2>&1;
if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi

if [ "$1" ] && $(echo "$1" | grep -q '^http'); then
  URL="$1";
  wget ${URL}/live/vmlinuz -O /mnt/live/vmlinuz 2>/dev/null;
  if [ $? -eq 0 ]; then 
    echo -e "  Copying immudex kernel to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
  fi
  wget ${URL}/live/initrd -O /mnt/live/initrd 2>/dev/null;
  if [ $? -eq 0 ]; then 
    echo -e "  Copying immudex initrd to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
  fi
  wget ${URL}/live/filesystem.squashfs -O /mnt/live/filesystem.squashfs 2>/dev/null;
  if [ $? -eq 0 ]; then
    echo -e "  Copying immudex filesystem.squashfs to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
  fi
  wget ${URL}/live/changelog -O /mnt/live/changelog 2>/dev/null;
  if [ $? -eq 0 ]; then 
    echo -e "  Copying immudex changelog file to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
  fi
    
  if $(sudo efibootmgr > /dev/null 2>&1); then
	  echo "  Copying grub config to the disk...";
    if [ "$1" ] && $(echo "$1" | grep -q '^http'); then
      wget ${URL}/live/grub.cfg -O /mnt/boot/grub/grub.cfg 2>/dev/null;
      if [ $? -eq 0 ]; then 
        echo -e "    Downloading immudex GRUB config...[ ${GREEN}OK${ENDCOLOR} ]";
      fi
      echo -e "  Copying grub config to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
    fi
    sed -i '/set\ timeout=/ s/30/5/' /mnt/boot/grub/grub.cfg;
	  sed -i 's/bootfrom=removable //g' /mnt/boot/grub/grub.cfg;
  fi

  umount -R /mnt;
  if [ $? -eq 0 ]; then
    echo -e "  Unmount immudex partition...[ ${GREEN}OK${ENDCOLOR} ]";
  fi
  echo -e "Upgrading immudex...[ ${GREEN}OK${ENDCOLOR} ]";
else
  help;
  exit 1;
fi
