#!/bin/bash

GREEN="\e[32m"
ENDCOLOR="\e[0m"

function yesNo() {
  PS3="YES/NO: ";
  echo "$1";
  select y0 in yes no; do
    if [ "$y0" = "yes" ]; then
      echo -n 1;
    fi
    break;
  done
}

echo -en "\e[1m"; echo "immudex" | /usr/bin/figlet | lolcat; echo -en "\e[0m";

lsblk;

echo -n "Put a disk device (name) with required space (10GB): ";
read diskDevice;

diskDeviceName=$(basename $diskDevice);
mountPoint="/media/sdk/${diskDeviceName}";
mkdir -p $mountPoint;

if $(echo $diskDevice | grep -q '/dev'); then
  mount $diskDevice $mountPoint;
else
  mount /dev/${diskDevice} $mountPoint;
fi

cd $mountPoint;
export HOME=$(pwd);

echo -n "Getting immudex project repository...";
if [ -d ~/immudex ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]";
else
  git clone https://github.com/xf0r3m/immudex >> /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
fi

PS3="ARCH: ";
echo "Chose a destination machine architecture:";
select a in amd64 i386; do
  ARCH=$a;
  break;
done;

PS3="DEBIAN: ";
echo "Chose a Debian base version:";
select d in oldstable stable testing; do
  DEBIAN=$d;
  break;
done;

eP=$(yesNo "Do you wanna add some extra packages?");
if [ "$eP" ]; then
  echo -n "Put space separated packages name list: ";
  read extraPackagesList;
  baseFilePath="~/immudex/versions/base.sh"; 
  tidyCommandLocation=$(grep -n 'tidy' $baseFilePath | tail -1 | cut -d ":" -f 1);
  extraPackagesListInstallationCommand="install_packages ${extraPackagesList};"
  sed -i "${tidyCommandLocation}i ${extraPackagesListInstaltionCommand}" $baseFilePath;
fi

eA=$(yesNo "Do you wanna add some extra addons?");
if [ "$eA" ]; then
  echo -n "Put space sparated addons name: ";
  read extraAddonsList;
  baseFilePath="~/immudex/versions/base.sh"; 
  for addonName in extraAddonsList; do
    tidyCommandLocation=$(grep -n 'tidy' $baseFilePath | tail -1 | cut -d ":" -f 1);
    extraAddonInstallationCommand="bash ~/immudex/addons/${addonName}";
    sed -i "${tidyCommandLocation}i ${extraAddonInstallationCommand}" $baseFilePath;
  done
fi

eS=$(yesNo "Do you wanna add some extra commands to base file?");
if [ "$eS" ]; then
  echo -n "Put script filepath: ";
  read scriptFilePath;
  baseFilePath="~/immudex/versions/base.sh"; 
  tidyCommandLocation=$(grep -n 'tidy' $baseFilePath | tail -1 | cut -d ":" -f 1);
  if $(head -1 $scriptFilePath | grep '#!/bin/bash'); then
    sed -n '2,$p' $scriptFilePath > /tmp/scriptSnippet.txt;
    sed -i "${tidyCommandLocation}r /tmp/scriptSnippet.txt" $baseFilePath;
  else
    sed -i "${tidyCommandLocation}r /tmp/scriptSnippet.txt" $baseFilePath;
  fi
fi

cN=$(yesNo "Do you wanna name this immudex image?";);
if [ "$cN" ]; then
  echo -n "Type your image name: ";
  read canonicalName;
fi

vER=$(yesNo "Do you wanna add version number?";);
if [ "$vER" ]; then
  echo -n "Type version of this image: ";
  if ! [ "$canonicalName" ]; then
    read canonicalName;
  else
    read version;
  fi
fi



#CMD="~/immudex/immudex-build --${ARCH} --${DEBIAN}";
#echo $CMD;

cat >> ${HOME}/XTerm <<EOF
xterm*faceName: Monospace
xterm*faceSize: 10
EOF

if [ "$DISPLAY" ]; then
  xterm -fg white -bg black -geometry 80x24 -e bash /usr/local/bin/immudex-build-show-log $HOME &
else
  echo "# The Logs preview isn't available. Your X server isn't running in this console. #";
  echo "# Logs are available in text file: ${HOME}/immudex_build.log #";
fi

if [ "$canonicalName" ] && [ "$version" ]; then
  ${HOME}/immudex/immudex-build --${ARCH} --${DEBIAN} $canonicalName $version;
elif [ "$canonicalName" ]; then
  ${HOME}/immudex/immudex-build --${ARCH} --${DEBIAN} $canonicalName;
else
  ${HOME}/immudex/immudex-build --${ARCH} --${DEBIAN};
fi



